import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning className='flex flex-col' lang='en'>
      <body
        className={'w-screen h-screen flex flex-col items-center justify-center'}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}